### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by madzat** [dfk7677/bfrcon-server#1]
Hi i need your help i have this error
(node:12764) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client

and i fixed with useMongoClient: true and now the Express server listening on port 5000 is stuck there any help

and if i check http://localhost:5000/ i have this error Cannot GET /

**Comment by dfk7677** [comment]
Hi, I updated mongoose to version 5 and the warning went away. As I don't own a BF server right now, I would appreciate it if you use the new version and tell me if everything is ok at your end.

**Comment by madzat** [comment]
Hi, ty for the fast reply i get more error
here 
C:\Sites\bfrcon-server-master>npm install
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated npm-registry-fetch@1.1.1: this version has a breaking change. use 1.1.0 or upgrade to latest
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm notice created a lockfile as package-lock.json. You should commit this file.
added 885 packages in 15.858s

C:\Sites\bfrcon-server-master>node server.js
loading configuration for environment : development
Connecting to: mongodb://localhost/bfrcon
Express server listening on port 5000
(node:8236) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (C:\Sites\bfrcon-server-master\node_modules\mongodb-core\lib\topologies\server.js:505:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (C:\Sites\bfrcon-server-master\node_modules\mongodb-core\lib\connection\pool.js:329:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (C:\Sites\bfrcon-server-master\node_modules\mongodb-core\lib\connection\connection.js:245:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:8236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Ps : i tested RCON web app and is have few problem 2

**Comment by dfk7677** [comment]
Hi again,
I updated node-mailer package to the latest so there is no deprecation error, but there seems to be another problem with your installation. Do you have a MongoDB server running accepting connections at port 27017?
If not, you have to change the connection string in [config.development.js](bfrcon-server/config/config.development.js), that is if you are using it for development (set in the config files too).

**Comment by madzat** [comment]
ty man i just fixed now  and please you explain how to added server plz

**Comment by dfk7677** [comment]
More info added in latest [commit](https://github.com/dfk7677/bfrcon-server/commit/5e9ced0113e73a76b38b3824d0dad2d59aa154df).
